name: Daily Vocabulary

on:
  schedule:
    - cron: '30 23 * * *' # åŒ—äº¬æ—¶é—´æ—©ä¸Š 7:30 å·¦å³
  workflow_dispatch:

permissions:
  contents: write

jobs:
  learn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - run: pip install requests
    
    - name: Fetch Word
      run: python vocabulary.py
      
    - name: Commit
      run: |
        git config --global user.email "huang@gshu.shop"
        git config --global user.name "huc-b4"
        
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "ğŸ“˜ Vocab: $(date +'%Y-%m-%d')" && git push)
